#!/bin/sh
#!/usr/bin/env bash
ORGANIZATION=$0
APPLICATION=$1
PROD_IPADDRESS=$2
GLOB_IPADDRESS=$3
PRO_USERID=$4
GLOB_USERID=$5
PRO_PASSWORD=$6
GLOB_PASSWORD=$7
PRO_PORT=$8
GLOB_PORT=$9
# ORGANIZATION="Exicom"
# APPLICATION="Xfusion_Platform"
# IPADDRESS="192.168.1.122"
# USERID="developer"
# PASSWORD="admin@123"
# PORT="3306"
echo "$ORGANIZATION"
echo "$APPLICATION"
echo "$PROD_IPADDRESS"
echo "$GLOB_IPADDRESS"
echo "$PRO_USERID"
echo "$GLOB_USERID"
echo "$PRO_PASSWORD"
echo "$GLOB_PASSWORD"
echo "$PRO_PORT"
echo "$GLOB_PORT"
. ./deployement.sh